"""add username to user model

Revision ID: 25d33d155df8
Revises: 8d2fc8357b7c
Create Date: 2026-06-18 17:16:41.222555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d33d155df8'
down_revision: Union[str, None] = '8d2fc8357b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'user',
        sa.Column('username', sa.String(length=50), nullable=True)
    )

    op.execute("""
        UPDATE "user"
        SET username = split_part(email, '@', 1)
    """)

    op.alter_column(
        'user',
        'username',
         nullable=False
    )

    op.create_index(
        op.f('ix_user_username'), 
        'user',
        ['username'], 
        unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
