name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACR_REGISTRY: application1.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      
      - name: login to ACR
        run: az acr login --name application1

        
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ env.ACR_REGISTRY }}/backend:latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ env.ACR_REGISTRY }}/frontend:latest
